# Generated by Django 3.2 on 2023-12-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionrecord',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='conversionrecord',
            name='word_file',
            field=models.FileField(upload_to=''),
        ),
    ]
