# Generated by Django 3.2 on 2023-12-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_word', '0003_auto_20231202_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionrecord',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='word_docs/'),
        ),
    ]
