# Generated by Django 3.2 on 2023-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_word', '0004_conversionrecord_word_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionrecord',
            name='pdf_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='conversionrecord',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
