# Generated by Django 3.2 on 2023-12-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_word', '0005_auto_20231207_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionrecord',
            name='pdf_file',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='conversionrecord',
            name='word_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
