# Generated by Django 3.2 on 2023-12-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_word', '0006_auto_20231212_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionrecord',
            name='pdf_file_name',
            field=models.CharField(default='default_name', max_length=100),
        ),
    ]
