# Generated by Django 3.2 on 2023-12-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_to_word', '0007_conversionrecord_pdf_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionrecord',
            name='word_file_name',
            field=models.CharField(default='default_name', max_length=100),
        ),
    ]
