# Generated by Django 3.2 on 2023-12-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=255)),
                ('available', models.CharField(max_length=100)),
                ('cancel', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(max_length=50),
        ),
    ]
